module.exports = [
    [
      {
        letter: 'T',
        entry: 'T',
        number: 1,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'W',
        entry: 'W',
        number: 2,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: '',
        number: 3,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'L',
        entry: 'L',
        number: 4,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'V',
        entry: 'V',
        number: 5,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: 6,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: 7,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: 8,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'I',
        entry: 'I',
        number: 9,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'N',
        entry: 'N',
        number: 10,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'N',
        entry: 'N',
        number: 11,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: 12,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'T',
        entry: 'T',
        number: 13,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: 'V',
        entry: 'V',
        number: 14,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'N',
        entry: 'N',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'M',
        entry: 'M',
        number: 15,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'D',
        entry: 'D',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'O',
        entry: 'O',
        number: 16,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'U',
        entry: 'U',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: 'M',
        entry: 'M',
        number: 17,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'D',
        entry: 'D',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'S',
        entry: 'S',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'C',
        entry: 'C',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: 18,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'M',
        entry: 'M',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'B',
        entry: 'B',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'L',
        entry: 'L',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'W',
        entry: 'W',
        number: 19,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'X',
        entry: 'X',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: 'A',
        entry: 'A',
        number: 20,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'L',
        entry: 'L',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'I',
        entry: 'I',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'S',
        entry: 'S',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'T',
        entry: 'T',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'B',
        entry: 'B',
        number: 21,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'B',
        entry: 'B',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'T',
        entry: 'T',
        number: 22,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'S',
        entry: 'S',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'N',
        entry: 'N',
        number: 23,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'O',
        entry: 'O',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'S',
        entry: '',
        number: 24,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'T',
        entry: 'T',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'I',
        entry: 'I',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'F',
        entry: 'F',
        number: 25,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'I',
        entry: 'I',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'D',
        entry: 'D',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: 'W',
        entry: 'W',
        number: 26,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: 27,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'G',
        entry: 'G',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'S',
        entry: 'S',
        number: 28,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'O',
        entry: 'O',
        number: 29,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'U',
        entry: 'U',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'T',
        entry: 'T',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'D',
        entry: 'D',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'O',
        entry: 'O',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: 'E',
        entry: 'E',
        number: 30,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'M',
        entry: 'M',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'U',
        entry: 'U',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'T',
        entry: 'T',
        number: 31,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: 32,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'I',
        entry: 'I',
        number: 33,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'B',
        entry: 'B',
        number: 34,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'U',
        entry: 'U',
        number: 35,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'T',
        entry: 'T',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: 'B',
        entry: 'B',
        number: 36,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'I',
        entry: 'I',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'P',
        entry: 'P',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'O',
        entry: 'O',
        number: 37,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'L',
        entry: 'L',
        number: 38,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'D',
        entry: 'D',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'I',
        entry: 'I',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'S',
        entry: 'S',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'O',
        entry: 'O',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'D',
        entry: 'D',
        number: 39,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: 40,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: 41,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'B',
        entry: 'B',
        number: 42,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'O',
        entry: 'O',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'O',
        entry: 'O',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'M',
        entry: 'M',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'O',
        entry: 'O',
        number: 43,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'D',
        entry: 'D',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: 'S',
        entry: 'S',
        number: 44,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'M',
        entry: 'M',
        number: 45,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: 46,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: 47,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'I',
        entry: 'I',
        number: 48,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: 49,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'G',
        entry: 'G',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'U',
        entry: 'U',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'N',
        entry: 'N',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: 'M',
        entry: 'M',
        number: 50,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'I',
        entry: 'I',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'X',
        entry: 'X',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'M',
        entry: 'M',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'S',
        entry: 'S',
        number: 51,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'T',
        entry: 'T',
        number: 52,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: 53,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: 54,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'M',
        entry: 'M',
        number: 55,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'G',
        entry: 'G',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: 'I',
        entry: 'I',
        number: 56,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'N',
        entry: 'N',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'C',
        entry: 'C',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'H',
        entry: 'H',
        number: 57,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'L',
        entry: 'L',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'O',
        entry: 'O',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'P',
        entry: 'P',
        number: 58,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'Y',
        entry: 'Y',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: 59,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'R',
        entry: 'R',
        number: 60,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: 'D',
        entry: 'D',
        number: 61,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'I',
        entry: 'I',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'D',
        entry: 'D',
        number: 62,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'I',
        entry: 'I',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'L',
        entry: 'L',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'Y',
        entry: 'Y',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'J',
        entry: 'J',
        number: 63,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'U',
        entry: 'U',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'M',
        entry: 'M',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'B',
        entry: 'B',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'L',
        entry: 'L',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: 'G',
        entry: 'G',
        number: 64,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'O',
        entry: 'O',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'P',
        entry: 'P',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'O',
        entry: 'O',
        number: 65,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'M',
        entry: 'M',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'N',
        entry: 'N',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'I',
        entry: 'I',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: 66,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'T',
        entry: 'T',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'A',
        entry: 'A',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'S',
        entry: 'S',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ],
    [
      {
        letter: 'E',
        entry: 'E',
        number: 67,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'N',
        entry: 'N',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'T',
        entry: 'T',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'W',
        entry: 'W',
        number: 68,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'T',
        entry: 'T',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'S',
        entry: 'S',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: '.',
        entry: '.',
        number: '',
        blackSquare: true,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square Square-Black',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'W',
        entry: 'W',
        number: 69,
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'D',
        entry: 'D',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'G',
        entry: 'G',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'E',
        entry: 'E',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      },
      {
        letter: 'D',
        entry: 'D',
        number: '',
        blackSquare: false,
        isChecked: false,
        displayWrong: false,
        isRevealed: false,
        className: 'Square',
        numberClassName: 'Square-Number',
        inputClassName: 'Square-Entry',
        noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
      }
    ]
  ]