module.exports = [
  [
    {
      letter: 'T',
      entry: '',
      number: 1,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'W',
      entry: '',
      number: 2,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 3,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'L',
      entry: '',
      number: 4,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'V',
      entry: '',
      number: 5,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 6,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 7,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 8,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'I',
      entry: '',
      number: 9,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'N',
      entry: '',
      number: 10,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'N',
      entry: '',
      number: 11,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 12,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'T',
      entry: '',
      number: 13,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: 'V',
      entry: '',
      number: 14,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'N',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'M',
      entry: '',
      number: 15,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'D',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'O',
      entry: '',
      number: 16,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'U',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: 'M',
      entry: '',
      number: 17,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'D',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'S',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'C',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 18,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'M',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'B',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'L',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'W',
      entry: '',
      number: 19,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'X',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: 'A',
      entry: '',
      number: 20,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'L',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'I',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'S',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'T',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'B',
      entry: '',
      number: 21,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'B',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'T',
      entry: '',
      number: 22,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'S',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'N',
      entry: '',
      number: 23,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'O',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'S',
      entry: '',
      number: 24,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'T',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'I',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'F',
      entry: '',
      number: 25,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'I',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'D',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: 'W',
      entry: '',
      number: 26,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 27,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'G',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'S',
      entry: '',
      number: 28,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'O',
      entry: '',
      number: 29,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'U',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'T',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'D',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'O',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: 'E',
      entry: '',
      number: 30,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'M',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'U',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'T',
      entry: '',
      number: 31,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 32,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'I',
      entry: '',
      number: 33,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'B',
      entry: '',
      number: 34,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'U',
      entry: '',
      number: 35,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'T',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: 'B',
      entry: '',
      number: 36,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'I',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'P',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'O',
      entry: '',
      number: 37,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'L',
      entry: '',
      number: 38,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'D',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'I',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'S',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'O',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'D',
      entry: '',
      number: 39,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 40,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 41,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'B',
      entry: '',
      number: 42,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'O',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'O',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'M',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'O',
      entry: '',
      number: 43,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'D',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: 'S',
      entry: '',
      number: 44,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'M',
      entry: '',
      number: 45,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 46,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 47,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'I',
      entry: '',
      number: 48,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 49,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'G',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'U',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'N',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: 'M',
      entry: '',
      number: 50,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'I',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'X',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'M',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'S',
      entry: '',
      number: 51,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'T',
      entry: '',
      number: 52,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 53,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 54,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'M',
      entry: '',
      number: 55,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'G',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: 'I',
      entry: '',
      number: 56,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'N',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'C',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'H',
      entry: '',
      number: 57,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'L',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'O',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'P',
      entry: '',
      number: 58,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'Y',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 59,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'R',
      entry: '',
      number: 60,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: 'D',
      entry: '',
      number: 61,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'I',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'D',
      entry: '',
      number: 62,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'I',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'L',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'Y',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'J',
      entry: '',
      number: 63,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'U',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'M',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'B',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'L',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: 'G',
      entry: '',
      number: 64,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'O',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'P',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'O',
      entry: '',
      number: 65,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'M',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'N',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'I',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 66,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'T',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'A',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'S',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ],
  [
    {
      letter: 'E',
      entry: '',
      number: 67,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'N',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'T',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'W',
      entry: '',
      number: 68,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'T',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'S',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: '.',
      entry: '',
      number: 0,
      blackSquare: true,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square Square-Black',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'W',
      entry: '',
      number: 69,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'D',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'G',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'E',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    },
    {
      letter: 'D',
      entry: '',
      number: 0,
      blackSquare: false,
      isChecked: false,
      displayWrong: false,
      isRevealed: false,
      className: 'Square',
      numberClassName: 'Square-Number',
      inputClassName: 'Square-Entry',
      noEditInputClassName: 'Square-Revealed-Text Square-No-Select'
    }
  ]
]
